### ISSUE TITLE
Action index.get_dir_content failed

### ISSUE THREAD

**Issue by Xanatos00** [envadrouillecorp/envadrouille#1]
Hi, 
On a fresh install:
```
Action index.get_dir_content failed (details) (Error 1/1)
This action has failed 1 time(s).
Last params:
    'action' => "index.get_dir_content"
    'dir' => "/"
    'limit' => "10"
    'random_sid' => "1639729411"

Last answer:
../photos/ is not a valid directory
```
The ../photos/ dir exist with 755 rights

Regards

**Comment by BLepers** [comment]
Hmm... I see two possible problems:

1/ The directory structure should look like that:
main_directory/
--admin/
--cache/
--photos/ <--- photo is in the main directory (../photos/ is relative to ./admin)
You can also use an absolute path in the administration to be sure /home/blabla/photos

2/ A permission issue? Is it 755 for the server or for yourself? (nginx or apache may run with a different username)

If it does not work, the code for index.get_dir_content is here https://github.com/envadrouillecorp/envadrouille/blob/master/admin/pages/index/index.php#L53 and the code probably fails when opening the directory here https://github.com/envadrouillecorp/envadrouille/blob/master/admin/common/php/file/dir.php#L28 (you can echo "$this->completePath" to see what the gallery tries to open).

**Comment by Xanatos00** [comment]
Indeed ! It's relative to ./admin, thanks !
